services:
  flowable:
    image: flowable/all-in-one:latest
    container_name: flowable-poc
    ports:
      - '8080:8080'
    depends_on:
      - flowable-db

  flowable-db:
    image: postgres:17
    container_name: flowable-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: flowable
      POSTGRES_USER: flowable
      POSTGRES_PASSWORD: flowable
    volumes:
      - flowable_postgres_data:/var/lib/postgresql/data

  app-db:
    image: postgres:17
    container_name: app-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: poc_document
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - app_postgres_data:/var/lib/postgresql/data

  keycloak-db:
    image: postgres:17
    container_name: keycloak-postgres
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.5
    container_name: keycloak
    command:
      - start-dev

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - '8081:8080'

    depends_on:
      - keycloak-db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-poc
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
volumes:
  flowable_postgres_data:
  app_postgres_data:
  keycloak_postgres_data:
